#!/bin/bash

[ -z "$1" ] && surf "https://bellanapoli.lu/notre-carte.html" && exit


if [ "$1" = "-b"  ]; then
    surf "https://duckduckgo.com"
else
    if echo "$1" | grep "^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$"; then
        surf "$1"
    else
        surf "https://duckduckgo.com/?q=$1&t=ffab&atb=v1-1"
    fi
fi
