#!/bin/sh
! echo "$1" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	notify-send "That doesn't look like a full URL." && exit

if [ -n "$2" ]; then
    case $2 in
	-y) RSSFILE="$HOME/.config/newsboat/youtube/urls" ;;
	*) notify-send "Dafuq you doing?" && exit
    esac
else
    RSSFILE="$HOME/.config/newsboat/urls"
fi

if awk '{print $1}' "$RSSFILE" | grep "^$1$" >/dev/null; then
	notify-send "You already have this RSS feed."
else
	echo "$1" >> "$RSSFILE" && notify-send "RSS feed added."
fi
