#!/bin/bash

master="bluez_sink.38_18_4C_BE_29_08.a2dp_sink"
sinkname="ALSA plug-in [firefox]"

pacmd load-module module-remap-sink sink_name="$sinkname" master="$master" channels=2 channel_map=mono,mono
