#!/bin/bash

new() {
    printf "New\n"
    mkdir ~/skola/ICT/$1
    cd ~/skola/ICT/$1
}


no_arg() {
    cd ~/skola/ICT
    lf
}

if [ -n $1 ];
then
    case $1 in
    	-n) new $2 ;;
	*) no_arg ;;
    esac
fi

